#####################
# IRC CONFIGURATION #
#####################

# This is the IRC server where you want to connect to
server: "play.vanilla-minecraft.fr"

# This is the port of the IRC Server.
# Warning, the port must be a port server (https://www.unrealircd.org/docs/Configuration#Listen_block)
port: 6900

# This is the password for the link (https://www.unrealircd.org/docs/Tutorial:_Linking_servers)
pass: "foxfox"

# This is the "Link" block. Its the server name of your bot.
link: "test.vanilla-minecraft.fr"

#You can put a description of what is that link in /map and /links on IRC
description: "Im an happy bridge between Minecraft and IRC"

# The channel where the users will appear when they are in game
channel: "#game"

# The channel where the log will appear
servicechannel: "#service"

# The main bot name, It's like the "operserv" from Anope.
botnick: "VanillaMinecraft"

# Put true if you want to debug IRC
irc-debug: true
